### ISSUE TITLE
Create JSON file to retrieve our information from

### ISSUE THREAD

**Issue by armandouv** [kendrajmoore/literate-tribble#7]
Since we are only three people I think that using a database to store our information would be overkill. In order to not hard code it into an HTML file, we could store it in a JSON file, parse it when the application starts, and use dynamic routes to render the templates containing the requested information.

For example:
Suppose the JSON file is:

{

    people: [
      {
           name: gigi,
           info: {<some attributes>},
      },
      {
          name: kendra,
          ...
      }
    ],
    
    projects: [
      {
          title: portfolio,
          ...more info    
      }
    ]

}

A dynamic route would look like /profiles/{name}, where name is a parameter.

Then, if I requested /profiles/gigi I'd get the profile template containing Gigi's info.
However, if I requested /profiles/someonewhodoesnotexist I'd get a 404 because it is not present in the JSON file.
What do you think?

**Comment by kendrajmoore** [comment]
Add project, profile json file
